### ISSUE TITLE
attributes with : in the name are being treated as a dot

### ISSUE THREAD

**Issue by jobweegink** [henrytseng/dataobject-parser#13]
'a.b:c'
will become 
`{a:
    {b:
      c{}
  }
}`

but should be
`{a:
    {'b:c':{}}
}`

**Comment by jobweegink** [comment]
you can fix it by changing line 57 from: 
`var re = /[\$\w-|]+|\[\]|([^\[[\w]\]]|["'](.*?)['"])/g;`
to
`var re = /[\$\w-:|]+|\[\]|([^\[[\w]\]]|["'](.*?)['"])/g;`
but I don't have rights to make a PR

**Comment by henrytseng** [comment]
Should be fixed now.
