### ISSUE TITLE
Prototype pollution vulnerability in dataobject-parser.js

### ISSUE THREAD

**Issue by lelecolacola123** [henrytseng/dataobject-parser#16]
Prototype pollution vulnerability in function set() in dataobject-parser.js in dataobject-parser1.2.22 via the function transpose
The function usevariable addObj lead to Prototype pollution in line 69

**Comment by henrytseng** [comment]
Can you open a PR with some tests?

**Comment by henrytseng** [comment]
https://github.com/henrytseng/dataobject-parser/pull/22
